### ISSUE TITLE
Multiple Windows Display Nothing

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/MyAnime3#39]
EDIT:
I've edited this issue to contain the results of the windows that display nothing when accessed. 

Skin: Titan

Images (Posters, Fanart and Wide Banners)
Series Info (AniDB and Groups)
Characters
Seiyuu
Relations

**Comment by RickDB** [comment]
Should be fixed in latest PR:

https://github.com/japanesemediamanager/MyAnime3/pull/40

MPEI wasn't installing the newer files and also some other Titan Extended ones, let me if it works with that one :)

**Comment by ElementalCrisis** [comment]
Hmm, I didn't use the MPEI as I copied the files directly from the release folder into their respective folders. Still an issue with the above not showing.

**Comment by RickDB** [comment]
So you copied both the .dll and skin files right from the top most /release folder right?
The latest MPEI maker file will install everything correctly now which is worth a try as that will rule out issues with locations :)

Tested here with Titan and Titan extended installed but everything had the proper label including that Something Random view, anything in mediaportal logs reporting a label mismatch of null reference?

**Comment by ElementalCrisis** [comment]
I'll have to check when I get home but the random window works, the ones I mentioned above don't display anything when selected.

**Comment by RickDB** [comment]
Btw the MPEI installer will also clear the skin cache by default as otherwise you might get old skin files.

**Comment by RickDB** [comment]
Not able to reproduce the bug yet in clean setups or current ones, suggest we move this to a later release after more testing :)

**Comment by ElementalCrisis** [comment]
Going to close this as I can no longer reproduce, going to assume it was something related to how MediaPortal was setup.
